export const categories = [
   {
      id: 1,
      name: 'Geral',
      image: require('../assets/img/pizzaIcon.png'),
   },
   {
      id: 2,
      name: 'Burger',
      image: require('../assets/img/icons8-hamburger-96.png'),
   },
   {
      id: 3,
      name: 'Italiana',
      image: require('../assets/img/icons8-spaghetti-96.png'),
   },
   {
      id: 4,
      name: 'Oriental',
      image: require('../assets/img/icons8-takeout-box-96.png'),
   },
   {
      id: 5,
      name: 'Peixe',
      image: require('../assets/img/icons8-tropical-fish-96.png'),
   },
   {
      id: 6,
      name: 'Doces',
      image: require('../assets/img/icons8-cupcake-emoji-96.png'),
   },
];

export const restaurantes = {
   id: 1,
   title: 'Apimentado!',
   description: 'Quente e marcante!',
   restaurants: [
      {
         id: 1,
         name: 'Papa Johns',
         image: require('../assets/img/pizza.jpg'),
         description: 'As Melhores pizzas!',
         lng: 38.2145602,
         lat: -85.5324269,
         address: '434 second street',
         stars: 4,
         review: '4.4k',
         category: 'Pizzaria',
         dishes: [
            {
               id: 1,
               name: 'Pizza Papas',
               description: 'Vários Sabores!',
               price: 35,
               image: require('../assets/img/pizzaDish.jpeg'),
            },
            {
               id: 2,
               name: 'Risotos',
               description: 'Deliciosos e Rápidos',
               price: 28,
               image: require('../assets/img/marmitex.jpg'),
            },
            {
               id: 3,
               name: 'Espetinho Cheese',
               description: 'Super Macio!',
               price: 22,
               image: require('../assets/img/queijinho.jpeg'),
            },
         ],
      },
      {
         id: 2,
         name: 'Taco Bell',
         image: require('../assets/img/tacobell.jpg'),
         description: 'Arriba! Muchachos!',
         lng: 38.2145602,
         lat: -85.5324269,
         address: '123 main street',
         stars: 5,
         review: '3.8k',
         category: 'Mexicana',
         dishes: [
            {
               id: 1,
               name: 'Taco',
               description: 'Varios Sabores',
               price: 22,
               image: require('../assets/img/taco1.jpeg'),
            },
            {
               id: 2,
               name: 'Burritos',
               description: 'Pra matar a fome',
               price: 34,
               image: require('../assets/img/burritos.jpg'),
            },
            {
               id: 3,
               name: 'Nachos',
               description: 'O Classico!',
               price: 40,
               image: require('../assets/img/nachos.jpg'),
            },
         ],
      },
      {
         id: 3,
         name: 'Komá Restaurante',
         image: require('../assets/img/coreana.jpg'),
         description: 'Comida Coreana de Qualidade!',
         lng: 38.2145602,
         lat: -85.5324269,
         address: '433 third street',
         stars: 3,
         review: '6.4k',
         category: 'Coreana',
         dishes: [
            {
               id: 1,
               name: 'Toppokki',
               description: 'Muito molho',
               price: 40,
               image: require('../assets/img/topokki.jpeg'),
            },
            {
               id: 2,
               name: 'Churrasco Coreano',
               description: 'No seu ponto!',
               price: 50,
               image: require('../assets/img/churrascocorea.jpg'),
            },
            {
               id: 3,
               name: 'Bibimbap',
               description: 'Tradicional Coreano',
               price: 38,
               image: require('../assets/img/bibimbap.jpg'),
            },
         ],
      },
   ],
}

export const restaurantes2 = {
   id: 1,
   title: 'Frango Frito',
   description: 'Crocante e Saboroso',
   restaurants: [
      {
         id: 1,
         name: 'Papa Johns',
         image: require('../assets/img/pizza.jpg'),
         description: 'As Melhores pizzas!',
         lng: 38.2145602,
         lat: -85.5324269,
         address: '434 second street',
         stars: 4,
         review: '4.4k',
         category: 'Pizzaria',
         dishes: [
            {
               id: 1,
               name: 'Pizza Papas',
               description: 'Vários Sabores!',
               price: 35,
               image: require('../assets/img/pizzaDish.jpeg'),
            },
            {
               id: 2,
               name: 'Risotos',
               description: 'Deliciosos e Rápidos',
               price: 28,
               image: require('../assets/img/marmitex.jpg'),
            },
            {
               id: 3,
               name: 'Espetinho Cheese',
               description: 'Super Macio!',
               price: 22,
               image: require('../assets/img/queijinho.jpeg'),
            },
         ],
      },
      {
         id: 2,
         name: 'Taco Bell',
         image: require('../assets/img/tacobell.jpg'),
         description: 'Arriba! Muchachos!',
         lng: 38.2145602,
         lat: -85.5324269,
         address: '123 main street',
         stars: 5,
         review: '3.8k',
         category: 'Mexicana',
         dishes: [
            {
               id: 1,
               name: 'Taco',
               description: 'Varios Sabores',
               price: 22,
               image: require('../assets/img/taco1.jpeg'),
            },
            {
               id: 2,
               name: 'Burritos',
               description: 'Pra matar a fome',
               price: 34,
               image: require('../assets/img/burritos.jpg'),
            },
            {
               id: 3,
               name: 'Nachos',
               description: 'O Classico!',
               price: 40,
               image: require('../assets/img/nachos.jpg'),
            },
         ],
      },
      {
         id: 3,
         name: 'Komá Restaurante',
         image: require('../assets/img/coreana.jpg'),
         description: 'Comida Coreana de Qualidade!',
         lng: 38.2145602,
         lat: -85.5324269,
         address: '433 third street',
         stars: 3,
         review: '6.4k',
         category: 'Coreana',
         dishes: [
            {
               id: 1,
               name: 'Toppokki',
               description: 'Muito molho',
               price: 40,
               image: require('../assets/img/topokki.jpeg'),
            },
            {
               id: 2,
               name: 'Churrasco Coreano',
               description: 'No seu ponto!',
               price: 50,
               image: require('../assets/img/churrascocorea.jpg'),
            },
            {
               id: 3,
               name: 'Bibimbap',
               description: 'Tradicional Coreano',
               price: 38,
               image: require('../assets/img/bibimbap.jpg'),
            },
         ],
      },
   ],
}

export const restaurantes3 = {
   id: 1,
   title: 'Comida Rápida!',
   description: 'Pra quem tem uma vida corrida!',
   restaurants: [
      {
         id: 1,
         name: 'Papa Johns',
         image: require('../assets/img/pizza.jpg'),
         description: 'As Melhores pizzas!',
         lng: 38.2145602,
         lat: -85.5324269,
         address: '434 second street',
         stars: 4,
         review: '4.4k',
         category: 'Pizzaria',
         dishes: [
            {
               id: 1,
               name: 'Pizza Papas',
               description: 'Vários Sabores!',
               price: 35,
               image: require('../assets/img/pizzaDish.jpeg'),
            },
            {
               id: 2,
               name: 'Risotos',
               description: 'Deliciosos e Rápidos',
               price: 28,
               image: require('../assets/img/marmitex.jpg'),
            },
            {
               id: 3,
               name: 'Espetinho Cheese',
               description: 'Super Macio!',
               price: 22,
               image: require('../assets/img/queijinho.jpeg'),
            },
         ],
      },
      {
         id: 2,
         name: 'Taco Bell',
         image: require('../assets/img/tacobell.jpg'),
         description: 'Arriba! Muchachos!',
         lng: 38.2145602,
         lat: -85.5324269,
         address: '123 main street',
         stars: 5,
         review: '3.8k',
         category: 'Mexicana',
         dishes: [
            {
               id: 1,
               name: 'Taco',
               description: 'Varios Sabores',
               price: 22,
               image: require('../assets/img/taco1.jpeg'),
            },
            {
               id: 2,
               name: 'Burritos',
               description: 'Pra matar a fome',
               price: 34,
               image: require('../assets/img/burritos.jpg'),
            },
            {
               id: 3,
               name: 'Nachos',
               description: 'O Classico!',
               price: 40,
               image: require('../assets/img/nachos.jpg'),
            },
         ],
      },
      {
         id: 3,
         name: 'Komá Restaurante',
         image: require('../assets/img/coreana.jpg'),
         description: 'Comida Coreana de Qualidade!',
         lng: 38.2145602,
         lat: -85.5324269,
         address: '433 third street',
         stars: 3,
         review: '6.4k',
         category: 'Coreana',
         dishes: [
            {
               id: 1,
               name: 'Toppokki',
               description: 'Muito molho',
               price: 40,
               image: require('../assets/img/topokki.jpeg'),
            },
            {
               id: 2,
               name: 'Churrasco Coreano',
               description: 'No seu ponto!',
               price: 50,
               image: require('../assets/img/churrascocorea.jpg'),
            },
            {
               id: 3,
               name: 'Bibimbap',
               description: 'Tradicional Coreano',
               price: 38,
               image: require('../assets/img/bibimbap.jpg'),
            },
         ],
      },
   ],
}
